platform:ios,"7.0"

target 'ScrollViewMenuDemo' do
    
pod 'AFNetworking', '~> 3.1.0'
pod 'DZNEmptyDataSet', '~> 1.8.1'
pod 'Masonry'
pod 'MJExtension', '~> 3.0.10'
pod 'MJRefresh', '~> 2.5.0'

pod 'SDWebImage', '~> 3.7.6'
pod 'YYCategories', '~> 1.0.2'
pod 'MBProgressHUD', '~> 0.9.2'

end
